<?php
$cmap = $this->cmap('');
$user = $this->identity();
?>

<script>
    let tables =  <?php echo json_encode($cmap['tables']); ?>

    let links = <?php echo json_encode($cmap['links']); ?>

    

</script>
<style>
    .table-foot-btn{
        fill:blue;
        font-size: 12px;
        text-decoration: underline;
        cursor: pointer;
        dominant-baseline: middle;
        /*text-anchor: middle;*/
    }
    .scroller_svg {
        overflow-y:auto;
        height:auto;
        max-height:800px;
        max-width: 1400px;
        scrollbar-width: thin;
        overflow-x: auto;
    }

    .tbClass{
        font-size: 12px;
    }
</style>

<form action="" method="post">
    <div>
      <button onclick="c.toImg()">toImg</button>
      <button onclick="c.downloadSVG()">toSvg</button>
      <?php
      if (isset($user) && $user->getId() > 0) {
      ?>
        <button onclick="c.savePos()">Sauvegarder</button>
      <?php
      }
      ?>
        <select name="cartes" id="cartes" onchange="javascript:this.form.submit()">
            <?php
            foreach ($cmap['lst_item_set'] as $id_i_s=>$title) {
            ?>
                <option value="<?= $id_i_s ?>" <?= $cmap['sel_carte'] == $id_i_s ? "selected" : "" ?>><?= $title ?></option>
            <?php
            }
            ?>
        </select>
    </div>
</form>
<div id="wrap" class="scroller_svg">
  <svg id="svg" xmlns="http://www.w3.org/2000/svg" style="border:1px dashed #000;background-color: #F8F8F9;"></svg>
</div>

<script>
    var c = new cmap({'width':1400,'height':800,'tables':tables, 'links':links})
</script>
