<?php
$cmap = $this->cmap('');
$user = $this->identity();
$path_img_loading = "/themes/default/img/loading.gif";
?>

<script>
    // Wait for window load
    $(window).load(function() {
        // Animate loader off screen
        $(".se-pre-con").fadeOut("slow");
    });

    let tables =  <?php echo json_encode($cmap['tables']); ?>

    let links = <?php echo json_encode($cmap['links']); ?>

    let site_url = "<?php echo $site->url(); ?>"

    function click_lst(v_carte){
        document.getElementById("cartes").value = v_carte;
        document.getElementById('frm_sel').submit();
        return false;
    }

</script>
<style>
    /* This only works with JavaScript,
    if it's not present, don't show loader */
    .no-js #loader { display: none;  }
    .js #loader { display: block; position: absolute; left: 100px; top: 0; }
    .se-pre-con {
        position: fixed;
        left: 600px;
        top: 150px;
        width: 10%;
        height: 10%;
        z-index: 9999;
        background: url(<?= $path_img_loading ?>) center no-repeat #fff;
    }

    .table-foot-btn{
        fill:blue;
        font-size: 12px;
        text-decoration: underline;
        cursor: pointer;
        dominant-baseline: middle;
        /*text-anchor: middle;*/
    }
    .scroller_svg {
        overflow-y:auto;
        height:auto;
        max-height:800px;
        max-width: 1400px;
        scrollbar-width: thin;
        overflow-x: auto;
    }

    .tbClass{
        font-size: 12px;
    }

    button, a.button, .resource-list.preview+a, [type="submit"], .but_cancel {
        background-color: #BFBFBF;
        color: #000;
    }
    .but_cancel:hover {
        color: #fff;
        background-color: #0d6efd;
        border-color: #0d6efd;
    }
</style>

<script>
    function show_add_carte() {
        document.getElementById('but_save_pos').style.visibility = 'hidden';
        $("#navbarSupportedContent li").hide();

        var x = document.getElementById("frm_add_carte");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }

        var y = document.getElementById("wrap");
        if (y.style.display === "block") {
            y.style.display = "none";
        } else {
            y.style.display = "block";
        }
    }

    function checkSelected() {
        var txt_name = document.getElementById('name_carte');
        if (txt_name.value === '') {
            alert('Entrer le nom de la carte');
            txt_name.focus();
            return false;
        } else {
            var checkboxes = document.getElementsByName("chk_class[]");
            var numberOfCheckedItems = 0;
            var str_pos_sel = "";
            for (var i = 0; i < checkboxes.length; i++) {
                if (checkboxes[i].checked) {
                    numberOfCheckedItems++;
                    if (str_pos_sel !== "") {
                        str_pos_sel += ",";
                    }
                    str_pos_sel += i;
                }
            }
            document.getElementById("pos_sel").value = str_pos_sel;

            if (numberOfCheckedItems == 0) {
                alert("Veuillez choisir au moins 1 class");
                return false;
            } else {
                frm_add.submit();
            }
        }
    }
</script>

<!-- colorimetrique --->
<div style="text-align: right">
    Entités: <svg id="seq1" width="80" height="20" ></svg> &nbsp;
    Propriétés: <svg id="seq2" width="80" height="20" ></svg> &nbsp;
    Relations: <svg id="seq3" width="80" height="20" ></svg> &nbsp;
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Carte des entités
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <form action="" method="post" id="frm_sel">
                        <?php
                        foreach ($cmap['lst_item_set'] as $id_i_s=>$title) {
                            ?>
                            <li><a class="dropdown-item <?= $cmap['sel_carte'] == $id_i_s ? "active" : "" ?>" href="#" onclick="click_lst(<?= $id_i_s ?>)"><?= $title ?></a></li>
                        <?php
                        }
                        ?>
                            <input type="hidden" name="cartes" id="cartes">
                        </form>
                    </ul>
                </li>
                <li class="nav-item" id="toImg">
                    <button class="btn btn-outline-success" onclick="c.toImg()">toImg</button>
                </li>
                <li class="nav-item" id="toSvg">
                    &nbsp;
                    <button class="btn btn-outline-success" onclick="c.downloadSVG()">toSvg</button>
                </li>
            </ul>
            <?php
            if (isset($user) && $user->getId() > 0) {
            ?>
            <div class="d-flex">
                <button class="btn btn-outline-success" onclick="c.savePos()" id="but_save_pos">Sauvegarder Position</button>
                &nbsp;&nbsp;&nbsp;
                <button class="btn btn-outline-success" onclick="show_add_carte()">Créer un nouvelle carte</button>
            </div>
                <?php
            }
            ?>
        </div>
    </div>
</nav>

<div id="wrap" class="scroller_svg" style="display: block">
  <svg id="svg" xmlns="http://www.w3.org/2000/svg" style="border:1px dashed #000;background-color: #F8F8F9;"></svg>
</div>

<div id="frm_add_carte" style="display: none; padding-top: 10px;">
    <div style="border:1px dashed #000;background-color: #F8F8F9; padding: 20px;">
    <form action="" method="post" id="frm_add" onsubmit="return checkSelected();">
        <div class="form-group row">
            <label for="inputName" class="col-sm-2 col-form-label">Nom carte <font color="#920b0b">*</font></label>
            <div class="col-sm-10">
                <input type="text" class="form-control"  name="name_carte" id="name_carte" placeholder="Nom carte">
            </div>
        </div>
        <fieldset class="form-group">
            <div class="row">
                <div class="col-sm-2">Les classes <font color="#920b0b">*</font></div>
                <div class="col-sm-10">
                    <div class="row">
                    <div class="col-sm-4">
                    <?php
                    $i = 1;
                    foreach ($cmap['chk_classes'] as $obj_class) {
                    ?>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridCheck1" name="chk_class[]" class="clonecheckbox" value="<?= $obj_class['label'] ?>">
                            <label class="form-check-label" for="gridCheck1">
                                <?= $obj_class['label'] ?>
                            </label>
                        </div>
                        <input type="hidden" name="term_class[]" value="<?= $obj_class['term'] ?>">
                    <?php
                        if ($i%3 == 0) {
                            print '</div><div class="col-sm-4">';
                        }

                        $i++;
                    }
                    ?>
                        <input type="hidden" name="pos_sel" id="pos_sel" value="">
                    </div>
                    </div>
                </div>
            </div>
        </fieldset>
        <div class="form-group row">
            <div class="col-sm-10" style="text-align: center;">
                <button type="submit" class="btn btn-primary">Sauvegarder</button>
                &nbsp;&nbsp;&nbsp;
                <a href="<?php echo $site->url(); ?>/page/cmap">
                    <input type="button" class="btn but_cancel" value="Annuler"/>
                </a>
            </div>
        </div>
    </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="postModal" tabindex="-1" aria-labelledby="postModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="postModalLabel">Notification</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
            </div>
        </div>
    </div>
</div>

<div class="se-pre-con"></div>

<script>
    var c = new cmap({'width':1400,'height':800,'tables':tables, 'links':links, 'site_url':site_url})
    c.drawScale("seq1", d3.interpolateRgb('white', 'red'));
    c.drawScale("seq2", d3.interpolateRgb('white', 'orange'));
    c.drawScale("seq3", d3.interpolateRgb('brown', 'blue'));
</script>
