<?php
$id = isset($_GET['id']) ? $_GET['id'] : 0;
$nb = isset($_GET['nb']) ? $_GET['nb'] : 0;
$nb_max = isset($_GET['mnb']) ? $_GET['mnb'] : 0;
$type = isset($_GET['type']) ? $_GET['type'] : "i";
$site_url = $site->url();
$user = $this->identity();
?>

<script>
    let colorProprietes = d3.scaleSequential()
        .domain([0,9])
        .interpolator(d3.interpolate("white", "orange"))
    colorProprietes.domain([0,<?= $nb_max ?>]);

    let colorTitleEntities = d3.scaleSequential()
        .domain([0,9])
        .interpolator(d3.interpolate("white", "red"))
    colorTitleEntities.domain([0,<?= $nb_max ?>]);
</script>

<ul class="nav nav-tabs" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="view-tab" data-bs-toggle="tab" data-bs-target="#view" type="button" role="tab" aria-controls="view" aria-selected="true">VOIR</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="edit-tab" data-bs-toggle="tab" data-bs-target="#edit" type="button" role="tab" aria-controls="edit" aria-selected="false">EDITIER</button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="color-tab" data-bs-toggle="tab" data-bs-target="#color" type="button" role="tab" aria-controls="color" aria-selected="false">VERIFIER</button>
    </li>
</ul>
<div class="tab-content" id="myTabContent" style="padding-top: 5px;">
    <div class="tab-pane fade show active" id="view" role="tabpanel" aria-labelledby="view-tab">
        <div class="ratio ratio-16x9">
            <iframe src="<?= $site_url ?>/item/<?= $id ?>" title="" allowfullscreen></iframe>
        </div>
    </div>
    <div class="tab-pane fade" id="edit" role="tabpanel" aria-labelledby="edit-tab">
        <?php
        if (isset($user) && $user->getId() > 0) {
        ?>
            <div class="ratio ratio-16x9">
                <iframe src="/admin/item/<?= $id ?>/edit" title="" allowfullscreen></iframe>
            </div>
        <?php
        } else {
        ?>
            <div style="padding-top: 20px;">
                Vous devez être connecté pour exécuter cette fonction.
            </div>
        <?php
        }
        ?>
    </div>
    <div class="tab-pane fade" id="color" role="tabpanel" aria-labelledby="color-tab" style="padding-top: 20px;">
        <?php
        $text_subjet = 'Entités';
        $text_detail = "La couleur d' entité de cet item";
        if ($type == 'p') {
            $text_subjet = 'Propriétés';
            $text_detail = 'La couleur de propriété de cet item';
        }
        ?>
        <?= $text_subjet ?>: <svg id="seq2" width="580" height="40" ></svg><br/><br/>
        <?= $text_detail ?>: <div id="res" style="text-align: center;"></div>
    </div>
</div>

<script>
    function drawScale(id, interpolator) {
        var data = Array.from(Array(10).keys());

        var cScale = d3.scaleSequential()
            .interpolator(interpolator)
            .domain([0,9]);

        var xScale = d3.scaleLinear()
            .domain([0,9])
            .range([0, 580]);

        var u = d3.select("#" + id)
            .selectAll("rect")
            .data(data)
            .enter()
            .append("rect")
            .attr("x", (d) => Math.floor(xScale(d)))
            .attr("y", 0)
            .attr("height", 40)
            .attr("width", (d) => {
                if (d == 9) {
                    return 6;
                }
                return Math.floor(xScale(d+1)) - Math.floor(xScale(d)) + 1;
            })
            .attr("fill", (d) => cScale(d));
    }

    if ("<?= $type ?>" == 'p') {
        drawScale("seq2", d3.interpolateRgb('white', 'orange'));
        document.getElementById('res').innerHTML = '<svg width="1000" height="200"><circle cx="50" cy="100" r="20" style="fill:' + colorProprietes(<?= $nb ?>) + ';"></circle></svg>';
    } else {
        drawScale("seq2", d3.interpolateRgb('white', 'red'));
        document.getElementById('res').innerHTML = '<svg width="1000" height="200"><circle cx="50" cy="100" r="20" style="fill:' + colorTitleEntities(<?= $nb ?>) + ';"></circle></svg>';
    }



</script>