<?php
$stats = $this->commentStats("all");
?>

<style type="text/css">
    .scroller {
        height: 100px;
        overflow-y: scroll;
        scrollbar-color: rebeccapurple green;
        scrollbar-width: thin;
    }

    .scroller_items {
        height: 300px;
        overflow-y: scroll;
        scrollbar-color: rebeccapurple green;
        scrollbar-width: thin;
    }
</style>

<div class="container-fluid" style="padding-top: 20px;padding-left: 0px; padding-right: 0px;">
    <div class="col col-md-12">
        <div class="row">
            <div class="col col-md-12">
                <h4>Commentaires Stats:</h4>
                Qui commente le plus: <?= $stats['arr_href_qui'][$stats['nom_qui_comment_plus']] ?> avec <a class="qui_comment_plus" data-toggle="collapse" href="#quiOne">items</a><span class="pull-right strong"><?= $stats['sum_qui_comment_plus'] ?> commentaire(s)</span>
                <div class="progress">
                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="<?= $stats['rate_qui_comment_plus'] ?>"aria-valuemin="0" aria-valuemax="100" style="width:<?= $stats['rate_qui_comment_plus'] ?>%"><?= $stats['value_qui_comment_plus'] ?> commentaire(s)</div>
                </div>
                <div class="collapse scroller" id="quiOne">
                Les items ont été commentés par <?= $stats['arr_href_qui'][$stats['nom_qui_comment_plus']] ?>: <br/>
                <?php
                foreach ($stats['arr_id_items_qui'][$stats['nom_qui_comment_plus']] as $item) {
                ?>
                    <a href="<?= $item['path'] ?>"> <?= $item['title'] ?> </a><br/>
                <?php
                }
                ?>
                </div>
                <br/>
                <?php
                foreach ($stats['arr_id_items_item'] as $item) {
                    if ($item['id'] == $stats['nom_item_comment_plus']) {
                        if (strlen($item['title']) > 50) {
                            $str_reply = substr($item['title'], 1, 45)." ...";
                        } else {
                            $str_reply = $item['title'];
                        }
                        $str_href = "<a href='".$item['path']."'>".$str_reply."</a>";
                    ?>
                        Quel item est le plus commentés: <?= $str_href ?><span class="pull-right strong"><?= $stats['sum_item_comment_plus'] ?> commentaire(s)</span>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?= $stats['rate_item_comment_plus'] ?>"aria-valuemin="0" aria-valuemax="100" style="width:<?= $stats['rate_item_comment_plus'] ?>%"><?= $stats['value_item_comment_plus'] ?> commentaire(s)</div>
                        </div>
                    <?php
                    }
                }
                ?>
                <br/>
                <?php
                foreach ($stats['arr_id_items_reply'] as $item) {
                    if (strcmp($item['comment'], $stats['nom_reply_comment_plus']) == 0) {
                        if (strlen($stats['nom_reply_comment_plus']) > 45) {
                            $str_reply = substr($stats['nom_reply_comment_plus'], 1, 50)." ...";
                        } else {
                            $str_reply = $stats['nom_reply_comment_plus'];
                        }
                        $str_href = "<a href='".$item['path']."'>".$str_reply."</a>";
                ?>
                    Quel commentaire a le plus de réponse: <?= $str_href ?><span class="pull-right strong"><?= $stats['sum_reply_comment_plus'] ?> réponse(s)</span>
                    <div class="progress">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="<?= $stats['rate_reply_comment_plus'] ?>"aria-valuemin="0" aria-valuemax="100" style="width:<?= $stats['rate_reply_comment_plus'] ?>%"><?= $stats['value_reply_comment_plus'] ?> réponse(s)</div>
                    </div>
                <?php
                    }
                }
                ?>

                <div style="padding-top: 50px;">
                    <div class="scroller_items">
                        <label>Les items commentées:</label>
                    <br/>
                    <?php
                    foreach ($stats['arr_id_items_item'] as $id=>$item) {
                        ?>
                        <a href='<?= $item['path'] ?>'> <?= $item['title'] ?></a> (<?= $stats['counts_item_comment_plus'][$id] ?> commentaire(s))<br/>
                        <?php
                    }
                    ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

