<?php
$stats = $this->commentStats("all");
?>

<style type="text/css">
    .scroller {
        overflow-y:auto;
        height:auto;
        max-height:200px;
        scrollbar-width: thin;
        overflow-x: hidden;
    }

    .scroller_items {
        overflow-y:auto;
        height:auto;
        max-height:300px;
        scrollbar-width: thin;
        overflow-x: hidden;
    }
</style>

<div class="container-fluid" style="padding-top: 20px;padding-left: 0px; padding-right: 0px;">
    <div class="col col-md-12">
        <div class="row">
            <div class="col col-md-4">
                <h4>Les personnes qui commentent le plus:</h4>
                <?php
                $i = 0;
                foreach ($stats['slice_counts_qui_comment_plus'] as $nom => $num_com) {
                    $rate = round(($num_com * 100) / $stats['sum_qui_comment_plus'], 1);
                ?>
                    <?= $stats['arr_href_qui'][$nom] ?> avec <a class="qui_comment_plus" data-toggle="collapse" href="#quiOne<?=$i?>">items</a><span class="pull-right strong"><?= $stats['sum_qui_comment_plus'] ?></span>
                    <div class="progress">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="<?= $rate ?>"aria-valuemin="0" aria-valuemax="100" style="width:<?= $rate ?>%"><?= $num_com > 1 ? $num_com." commentaires" : $num_com." commentaire" ?></div>
                    </div>
                    <div class="collapse scroller" id="quiOne<?=$i?>">
                    <?php
                    foreach ($stats['arr_id_items_qui'][$nom] as $item) {
                    ?>
                        <a href="<?= $site->url() ?>/item/<?= $item['id'] ?>"> <?= "- ".$item['title'] ?> </a><br/>
                    <?php
                    }
                    ?>
                        <br/>
                    </div>
                <?php
                    $i++;
                }
                ?>
            </div>
            <div class="col col-md-4">
                <h4>Les items qui sont le plus commentés:</h4>
                <?php
                foreach ($stats['slice_counts_item_comment_plus'] as $item_id => $num_com) {
                $rate = round(($num_com * 100) / $stats['sum_item_comment_plus'], 1);
                ?>
                <?php
                foreach ($stats['arr_id_items_item'] as $item) {
                    if ($item['id'] == $item_id) {
                        if (strlen($item['title']) > 20) {
                            $str_reply = substr($item['title'], 0, 20)." ...";
                        } else {
                            $str_reply = $item['title'];
                        }
                        $str_href = "<a href='".$site->url()."/item/".$item['id']."' title='".$item['title']."'>".$str_reply."</a>";
                    ?>

                        <?= $str_href ?><span class="pull-right strong"><?= $stats['sum_item_comment_plus'] ?></span>
                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="<?= $rate ?>"aria-valuemin="0" aria-valuemax="100" style="width:<?= $rate ?>%"><?= $num_com > 1 ? $num_com." commentaires" : $num_com." commentaire" ?></div>
                        </div>
                    <?php
                    }
                }
                ?>
                <?php
                }
                ?>
            </div>
            <div class="col col-md-4">
                <h4>Les commentaires qui ont le plus de réponse:</h4>
                <?php
                foreach ($stats['slice_counts_reply_comment_plus'] as $com => $num_reply) {
                $rate = round(($num_reply * 100) / $stats['sum_reply_comment_plus'], 1);
                ?>
                <?php
                foreach ($stats['arr_id_items_reply'] as $id=>$item) {
                    if (strcmp($item['comment'], $com) == 0) {
                        if (strlen($com) > 20) {
                            $str_reply = substr($com, 0, 20)." ...";
                        } else {
                            $str_reply = $com;
                        }
                        $str_href = "<a href='".$site->url()."/item/".$id."' title='".$com."'>".$str_reply."</a>";
                ?>

                    <?= $str_href ?><span class="pull-right strong"><?= $stats['sum_reply_comment_plus'] ?></span>
                    <div class="progress">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="<?= $rate ?>"aria-valuemin="0" aria-valuemax="100" style="width:<?= $rate ?>%"><?= $num_reply > 1 ? $num_reply." réponses" : $num_reply." réponse" ?></div>
                    </div>
                <?php
                    }
                }
                ?>
                <?php
                }
                ?>
            </div>
        </div>
        <div style="padding-top: 50px;">
            <div class="scroller_items">
                <label>Les items commentées:</label>
                <br/>
                <?php
                foreach ($stats['arr_id_items_item'] as $id=>$item) {
                    ?>
                    <a href='<?= $site->url() ?>/item/<?= $item['id'] ?>'> <?= "- ".$item['title'] ?></a> (<?= $stats['counts_item_comment_plus'][$id] > 1 ? $stats['counts_item_comment_plus'][$id]." commentaires" : $stats['counts_item_comment_plus'][$id]." commentaire" ?> )<br/>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>