<?php
$cmap = $this->vars('cmap');
$site = $this->vars('site');
?>
<script>
    function checkSelected() {
        var txt_name = document.getElementById('name_carte');
        if (txt_name.value === '') {
            alert('Entrer le nom de la carte');
            txt_name.focus();
            return false;
        } else {
            var checkboxes = document.getElementsByName("chk_class[]");
            var numberOfCheckedItems = 0;
            var str_pos_sel = "";
            for (var i = 0; i < checkboxes.length; i++) {
                if (checkboxes[i].checked) {
                    numberOfCheckedItems++;
                    if (str_pos_sel !== "") {
                        str_pos_sel += ",";
                    }
                    str_pos_sel += i;
                }
            }
            document.getElementById("pos_sel").value = str_pos_sel;

            if (numberOfCheckedItems == 0) {
                alert("Veuillez choisir au moins 1 class");
                return false;
            } else {
                frm_add.submit();
            }
        }
    }

    function show_add_carte() {
        document.getElementById('but_save_pos').style.visibility = 'hidden';
        $("#navbarSupportedContent li").hide();

        var x = document.getElementById("frm_add_carte");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }

        var y = document.getElementById("wrap");
        if (y.style.display === "block") {
            y.style.display = "none";
        } else {
            y.style.display = "block";
        }

        var z = document.getElementById("colorimetrique");
        if (z.style.display === "block") {
            z.style.display = "none";
        } else {
            z.style.display = "block";
        }
    }
</script>
<style>
    button, a.button, .resource-list.preview+a, [type="submit"], .but_cancel {
        background-color: #BFBFBF;
        color: #000;
    }
    .but_cancel:hover {
        color: #fff;
        background-color: #0d6efd;
        border-color: #0d6efd;
    }
</style>
<div id="frm_add_carte" style="display: none; padding-top: 10px;">
    <div style="border:1px dashed #000;background-color: #F8F8F9; padding: 20px;">
        <form action="" method="post" id="frm_add" onsubmit="return checkSelected();">
            <div class="form-group row">
                <label for="inputName" class="col-sm-2 col-form-label">Nom carte <font color="#920b0b">*</font></label>
                <div class="col-sm-10">
                    <input type="text" class="form-control"  name="name_carte" id="name_carte" placeholder="Nom carte">
                </div>
            </div>
            <fieldset class="form-group">
                <div class="row">
                    <div class="col-sm-2">Les classes <font color="#920b0b">*</font></div>
                    <div class="col-sm-10">
                        <div class="row">
                            <div class="col-sm-4">
                                <?php
                                $i = 1;
                                foreach ($cmap['chk_classes'] as $obj_class) {
                                    ?>
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="gridCheck1" name="chk_class[]" class="clonecheckbox" value="<?= $obj_class['label'] ?>">
                                        <label class="form-check-label" for="gridCheck1">
                                            <?= $obj_class['label'] ?>
                                        </label>
                                    </div>
                                    <input type="hidden" name="term_class[]" value="<?= $obj_class['term'] ?>">
                                    <?php
                                    if ($i%3 == 0) {
                                        print '</div><div class="col-sm-4">';
                                    }

                                    $i++;
                                }
                                ?>
                                <input type="hidden" name="pos_sel" id="pos_sel" value="">
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="form-group row">
                <div class="col-sm-10" style="text-align: center;">
                    <button type="submit" class="btn btn-primary">Sauvegarder</button>
                    &nbsp;&nbsp;&nbsp;
                    <a href="<?php echo $site->url(); ?>/page/cmap">
                        <input type="button" class="btn but_cancel" value="Annuler"/>
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>