<?php
$cmap = $this->vars('cmap');
$user = $this->vars('user');
?>
<script>
    function click_lst(v_carte){
        document.getElementById("cartes").value = v_carte;
        document.getElementById('frm_sel').submit();
        return false;
    }
</script>
<style>
    @media (min-width:375px) {
        .navbar-expand-lg {
          -webkit-box-orient: horizontal;
          -webkit-box-direction: normal;
          -ms-flex-flow: row nowrap;
          flex-flow: row nowrap;
          -webkit-box-pack: start;
          -ms-flex-pack: start;
          justify-content: flex-start;
        }
        .navbar-expand-lg .navbar-nav {
          -webkit-box-orient: horizontal;
          -webkit-box-direction: normal;
          -ms-flex-direction: row;
          flex-direction: row;
        }
        .navbar-expand-lg .navbar-nav .dropdown-menu {
          position: absolute;
        }
        .navbar-expand-lg .navbar-nav .dropdown-menu-right {
          right: 0;
          left: auto;
        }
        .navbar-expand-lg .navbar-nav .nav-link {
          padding-right: 0.5rem;
          padding-left: 0.5rem;
        }
        .navbar-expand-lg > .container,
        .navbar-expand-lg > .container-fluid {
          -ms-flex-wrap: nowrap;
          flex-wrap: nowrap;
        }
        .navbar-expand-lg .navbar-collapse {
          display: -webkit-box !important;
          display: -ms-flexbox !important;
          display: flex !important;
          -ms-flex-preferred-size: auto;
          flex-basis: auto;
        }
        .navbar-expand-lg .navbar-toggler {
          display: none;
        }
        .navbar-expand-lg .dropup .dropdown-menu {
          top: auto;
          bottom: 100%;
        }
      }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Carte des entités
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <form action="" method="post" id="frm_sel">
                        <?php
                        foreach ($cmap['lst_item_set'] as $id_i_s=>$title) {
                            ?>
                            <li><a class="dropdown-item <?= $cmap['sel_carte'] == $id_i_s ? "active" : "" ?>" href="#" onclick="click_lst(<?= $id_i_s ?>)"><?= $title ?></a></li>
                        <?php
                        }
                        ?>
                            <input type="hidden" name="cartes" id="cartes">
                        </form>
                    </ul>
                </li>
                <li class="nav-item" id="toImg">
                    <button class="btn btn-outline-success" onclick="c.toImg()">toImg</button>
                </li>
                <li class="nav-item" id="toSvg">
                    &nbsp;
                    <button class="btn btn-outline-success" onclick="c.downloadSVG()">toSvg</button>
                </li>
            </ul>
            <?php
            if (isset($user) && $user->getId() > 0) {
            ?>
            <div class="d-flex">
                <button class="btn btn-outline-success" onclick="c.savePos()" id="but_save_pos">Sauvegarder Position</button>
                <?php
                if ($cmap['name_entite'] == '') {
                ?>
                    &nbsp;&nbsp;&nbsp;
                    <button class="btn btn-outline-success" onclick="show_add_carte()">Créer un nouvelle carte</button>
                <?php
                }
                ?>
            </div>
            <?php
            }
            ?>
        </div>
    </div>
</nav>