<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

?>

<style type="text/css">
    body.resource #content>h2:first-of-type+h3 {
        font-size: 15px;
        text-transform: uppercase;
        margin: -30px 0 30px;
    }
    h3 {
        font-size: 15px;
        text-transform: uppercase;
        margin: -30px 0 30px;
        line-height: 45px;
        display: block;
        margin-block-start: 1em;
        margin-block-end: 1em;
        margin-inline-start: 0px;
        margin-inline-end: 0px;
        font-weight: bold;
    }
    h4 {
        margin-bottom: 0;
        font-size: 15px;
    }

    h2 {
        margin: 0px;
    }

    .scroller {
        overflow-y:auto;
        height:auto;
        max-height:602px;
        scrollbar-width: thin;
        overflow-x: hidden;
    }

    .comment {
        margin-left: 0px;
    }

    .uv .headerPanel .centerOptions .search .searchText {
        color: #565656;
    }

    .field .inputs>select, .field .inputs>textarea, .field .inputs>input[type="text"], .field .inputs>input[type="password"], .field .inputs>input[type="email"], .field .inputs>input[type="url"] {
        font-size: 14px;
    }
</style>
<div class="container" style="padding-top: 20px;">
    <?php echo $this->pageTitle($item->displayTitle(), 2); ?>
</div>
<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 frm_left">
    <div class="recent_news_frame_left">
    <div style="padding-top: 13px;"></div>
    <?php echo $this->universalViewer($resource); ?>
</div>
</div>
<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 frm_right">
    <div class="right_1">
        <!--- begin comment----->
        <div class="comment">
            <div class="be-comment-block scroller">
                <?php echo $this->showComments($resource); ?>
                <?php echo $this->showCommentForm($resource); ?>
            </div>
        </div>
        <!--- end comment------->
    </div>
    <div class="right_2">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <!--- begin tags----->
            <?php echo $this->showTags($resource); ?>
            <?php echo $this->showTaggingForm($resource); ?>
            <!--- end tags----->
        </div>
    </div>
</div>

<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <?php
        $plugins = $this->getHelperPluginManager();
        $hasNext = $plugins->has('previousResource');
        ?>
        <?php if ($hasNext): ?>
            <div class="previous-next-items">
                <?php if ($previous = $this->previousResource($resource)): ?>
                    <?= $previous->link($translate('Previous item'), null, ['class' => 'previous-item']) ?>
                <?php endif; ?>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?php if ($next = $this->nextResource($resource)): ?>
                    <?= $next->link($translate('Next item'), null, ['class' => 'next-item']) ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</div>
