<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$userBarComment = $this->userBarComment();
?>

<div class="container">
    <div class="col-lg-3 col-md-7 col-sm-5 col-xs-12">
        <div class="logo">
            <?php if ($this->themeSetting('logo')): ?>
                <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
            <?php else: ?>
                <?php echo $escape($siteTitle); ?>
            <?php endif; ?>
        </div>
    </div>
    <?php echo $userBarComment;?>



