<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation[] $comments
 * @var bool $commentThreaded
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$url = $plugins->get('url');
$setting = $plugins->get('setting');
$assetUrl = $plugins->get('assetUrl');
$partial = $plugins->get('partial');

$this->headLink()->appendStylesheet($assetUrl('css/comment.css', 'Comment'));
$this->headScript()->appendFile($assetUrl('js/comment.js', 'Comment'), 'text/javascript', ['defer' => 'defer']);

// Required to manage the base path.
$addUrl = $url('site/comment', ['action' => 'add'], true);
?>

<div id="comments" class="comments" data-comment-url="<?= $addUrl ?>">
    <?php
        if ($label = $setting('comment_comments_label')):
            $count_com = 0;
            foreach ($comments as $comment) {
                $parent = $comment->parent();
                if (($parent && $parent->id() == $comment->id()) || (empty($parent) && empty($parent_id))) {
                    $count_com++;
                }
            }
            if (empty($comments)):
                echo "<h2>Commentaires</h2>";
            else:
    ?>
                <h2>
                    <?= $count_com > 1 ? $count_com." Commentaires" : $count_com." Commentaire" ?>
                </h2>
    <?php
            endif;
        endif;
    ?>
    <?php if (empty($comments)): ?>
    <p><?= $translate('No comment yet! Be the first to add one!') ?></p>
    <?php elseif ($setting('comment_threaded')): ?>
        <?= $partial('common/comments-thread', ['comments' => $comments, 'parent_id' => null]) ?>
    <?php else: ?>
        <?= $partial('common/comments-list', ['comments' => $comments]) ?>
    <?php endif; ?>
</div>
