<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Api\Representation\CommentRepresentation $comment
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
$hyperlink = $plugins->get('hyperlink');
$userIsAllowed = $plugins->get('userIsAllowed');
$i18n = $plugins->get('i18n');
$setting = $plugins->get('setting');

if ($name = $comment->name()):
    $website = $comment->website();
    $authorText = $website ? $hyperlink($name, $website) : $name;
else:
    $authorText = $escape($translate('Anonymous'));
endif;

$gravatarUrl = '//www.gravatar.com/avatar/' . md5(strtolower(trim($comment->email())));
?>

<style type="text/css">
    .comment .comment-flag, .comment .comment-unflag {
        padding-left: 0px;
    }
    .comment .comment-spam, .comment .comment-flagged {
        background-color: #EB7976;
    }
    .comment .comment-spam, .comment .comment-flagged .be-comment-time {
        font-size: 11px;
        color: #64727F;
        padding-right: 2px;
    }
    .comment .comment-spam, .comment .comment-flagged .be-comment-name {
        padding-left: 5px;
    }
    .count_comment_children
    {
        text-align: right;
        font-size: 12px;
    }
    .count_comment_children:hover
    {
        color:#ff9138;
        cursor:pointer;
    }
    .be-ava-comment-thumb {
        width: 24px;
        height: 24px;
        border-radius: 50%;
    }
    .be-img-comment-thumb {
        width: 24px;
        height: 24px;
        float: left;
        margin-bottom: 5px;
        padding-top: 8px;
    }
    .be-comment-content-thumb {
        margin-left: 30px;
    }
    .be-comment-time-thumb {
        float: right;
        font-size: 11px;
        color: #b4b7c1;
    }
</style>
<?php if ($count > 0): ?>
<div class="count_comment_children" data-toggle="collapse" href="#replyOne<?= $escape($comment->id()) ?>">
    <?= $count > 1 ? $count . " Réponses" : $count . " Réponse" ?>
</div>
<?php endif; ?>
<?php
$parent = $comment->parent();
$str_con = "";
if (($parent && $parent->id() == $comment->id()) || (empty($parent) && empty($parent_id))) {
    $str_con = "";
} else {
    $str_con = "-thumb";
}
?>
<div class="be-comment">
    <div class="be-img-comment<?= $str_con ?>">
        <img class="be-ava-comment<?= $str_con ?>" src="<?= $gravatarUrl ?>" />
    </div>

<div class="be-comment-content<?= $str_con ?>">
<div class="comment-body<?php if ($flagged = $comment->isFlagged()): ?> comment-flagged<?php endif; ?><?php if ($comment->isSpam()): ?> comment-spam<?php endif; ?>">
    <span class="be-comment-name">
        <?= $authorText ?>
    </span>
    <span class="be-comment-time<?= $str_con ?>">
        <i class="fa fa-clock-o"></i>
        <?= $i18n->dateFormat($comment->created()) ?>
    </span>
    <p class="be-comment-text">
        <?= $escape($comment->body()) ?>
    </p>
</div>
</div>
</div>

<div class="social_network">
    <ul>
<?php
    // Don't display the flag when the comments are moderated a priori.
?>
<?php if ((!$setting('comment_public_require_moderation') || !$setting('comment_user_require_moderation')) && ($parent && $parent->id() == $comment->id()) || (empty($parent) && empty($parent_id))): ?>

    <?php if ($userIsAllowed(\Comment\Controller\Site\CommentController::class, 'flag')): ?>
        <li><i class="fa fa-flag comment-flag"<?php if ($flagged): ?> style="display:none;"<?php endif;?> title="<?= $escape($translate('Flag inappropriate')) ?>"></i></li>
    <?php endif; ?>
    <?php if ($userIsAllowed(\Comment\Controller\Site\CommentController::class, 'unflag')): ?>
        <li><i class="fa fa-flag comment-unflag"<?php if (!$flagged): ?> style="display:none;"<?php endif;?> title="<?= $escape($translate('Unflag inappropriate')) ?>"></i></li>
    <?php endif; ?>

<?php endif; ?>

<?php if ($count > 0): ?>
        <li><i class="count-comment fa fa-comment" data-toggle="collapse" href="#replyOne<?= $escape($comment->id()) ?>" title="<?= $count > 1 ? $count . " Réponses" : $count . " Réponse" ?>"></i></li>
<?php endif; ?>

<?php if ($comment->userIsAllowed('create') && ($parent && $parent->id() == $comment->id()) || (empty($parent) && empty($parent_id))): ?>
    <li><i class="comment-reply fa fa-reply" title="<?= $escape($translate('Reply')) ?>"></i></li>
<?php endif; ?>

    </ul>
</div>