<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Comment\Form\CommentForm $commentForm
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$formElement = $plugins->get('formElement');
$formLabel = $plugins->get('formLabel');
$formText = $plugins->get('formText');
$formHidden = $plugins->get('formHidden');

$user = $this->identity();
$isAnonymous = empty($user);

$commentForm->prepare();
?>

<style type="text/css">
    @media screen and (max-width:767px) {
        input[type=checkbox], input[type=radio]  {
            margin: 0px;
        }
    }
    .form-group {
        margin-bottom: 5px;
    }
</style>

<div class="form-block">
    <div id="comment-main-container" data-is-anonymous="<?= (int) $isAnonymous ?>">
    <?php // echo $this->form($commentForm) ?>
    <?php // TODO Add messages only if not set by layout. Anyway, they are available via json. ?>
    <?php if (false && $messages = $this->messages()): ?>
    <div id="comments-flash"><?= $messages ?></div>
    <?php endif; ?>

    <?= $this->form()->openTag($commentForm) ?>

    <div class="row">
<?php if ($isAnonymous): ?>
    <?php $element = $commentForm->get('o:name'); ?>
    <div class="col-xs-12 col-sm-6">
        <div class="form-group">
            <input class="form-input inputs" type="text" placeholder="Mon nom..." name="o:name">
        </div>
    </div>

    <?php $element = $commentForm->get('o:email'); ?>
    <div class="col-xs-12 col-sm-6">
        <div class="form-group">
            <input class="form-input" required="required" type="text" placeholder="Mon email (pas afficher)..." name="o:email">
        </div>
    </div>

    <?php $element = $commentForm->get('o-module-comment:website'); ?>
    <div class="col-xs-12">
        <div class="form-group">
            <input class="form-input" type="text" placeholder="Mon site internet..." name="o-module-comment:website">
        </div>
    </div>

<?php endif; ?>

    <?php $element = $commentForm->get('o-module-comment:body'); ?>
    <div class="col-xs-12">
        <div class="form-group">
            <textarea class="form-input" required="required" placeholder="Mon commentaire..." name="o-module-comment:body"></textarea>
        </div>
    </div>

<?php if ($isAnonymous): ?>
    <?php if ($commentForm->has('recaptcha')): ?>
    <?php $element = $commentForm->get('recaptcha'); ?>
    <div class="col-xs-12">
        <div class="form-group inputs" required="required">
            <?= $formElement($element) ?>
        </div>
    </div>

    <?php endif; ?>
    <?php if ($commentForm->has('o-module-comment:check')): /* honeyspot */ ?>
    <?php $element = $commentForm->get('o-module-comment:check'); ?>
    <div class="col-xs-12">
        <div class="form-group inputs" required="required">
            <?= $formElement($element) ?>
        </div>
    </div>

    <?php endif; ?>
    <?php if ($commentForm->has('address')): /* quick anti-robot */ ?>
    <?php $element = $commentForm->get('address'); ?>

    <div class="col-xs-12">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs" required="required">
            <?= $formElement($element) ?>
        </div>
    </div>

    <?php $element = $commentForm->get('address_a'); ?>
    <?= $formHidden($element) ?>
    <?php $element = $commentForm->get('address_b'); ?>
    <?= $formHidden($element) ?>
    <?php endif; ?>
    <?php if ($commentForm->has('legal_agreement')): ?>
    <?php $element = $commentForm->get('legal_agreement'); ?>
    <div class="col-xs-12" style="padding-top: 5px;">
        <div class="form-group inputs" required="required">
            <?= $this->formCheckbox($element)." ".rtrim(ltrim($this->setting('comment_legal_text'),"<p>"), "</p>") ?>
        </div>
    </div>

    <?php endif; ?>
<?php endif; ?>

    <?= $formHidden($commentForm->get('resource_id')) ?>
    <?= $formHidden($commentForm->get('comment_parent_id')) ?>
    <?= $formHidden($commentForm->get('path')) ?>
    <?= $formHidden($commentForm->get('csrf_' . $resource->id())) ?>
    <?= $formHidden($commentForm->get('csrf')) ?>
    <?php $element = $commentForm->get('submit'); ?>

    <div class="col-xs-12">
        <div class="form-group inputs pull-right" required="required">
            <?= $this->formInput($element) ?>
        </div>
    </div>

    <?php //echo $this->formButton()->openTag($element) ?>
    <?php //echo $formLabel($element) ?>
    <?php //echo $this->formButton()->closeTag() ?>
    <?= $this->form()->closeTag() ?>
    </div>
</div>
</div>
